### Create new user
POST http://localhost:3333/api/auth/signup
content-type: application/json

{
    "username": "knight",
    "email": "knight.sarai.dev2@gmail.com",
    "password": "1234455."
}

### Signin
POST http://localhost:3333/api/auth/signin
content-type: application/json

{
    "email": "knight.sarai.dev2@gmail.com",
    "password": "1234455."
}

### Signout
POST http://localhost:3333/api/auth/signout
content-type: application/json

{
    "email": "knight.sarai.dev2@gmail.com",
    "password": "1234455."
}
 
### Get User
GET http://localhost:3333/api/auth/me
 
### Get User By ID
GET http://localhost:3333/api/auth/?id=1


### Create fight
POST http://localhost:3333/api/fights
content-type: application/json

{
    "age": 33,
    "wins":  40,
    "losses": 4,
    "draws": 2,
    "rounds": 3,
    "price": 10000
}

### Approve Fight
PATCH  http://localhost:3333/api/fights/8
content-type: application/json

{
    "approved": true
}


### Get estimate
GET http://localhost:3333/api/fights/?age=28&wins=30&losses=3&draws=1&rounds=3


