### Create new user
POST http://localhost:3333/api/auth/signup
content-type: application/json

{
    "username": "knight",
    "email": "knight.sarai.dev2@gmail.com",
    "password": "1234455."
}

### Signin
POST http://localhost:3333/api/auth/signin
content-type: application/json

{
    "email": "knight.sarai.dev2@gmail.com",
    "password": "1234455."
}

### Signout
POST http://localhost:3333/api/auth/signout
content-type: application/json

{
    "email": "knight.sarai.dev2@gmail.com",
    "password": "1234455."
}
 
### Get User
GET http://localhost:3333/api/auth/me

### Create fight
POST http://localhost:3333/api/fights
content-type: application/json

{
    "age": 27,
    "wins":  12,
    "losses": 5,
    "draws": 1,
    "rounds": 3,
    "price": 500
}

### Approve Fight
PATCH  http://localhost:3333/api/fights/5
content-type: application/json

{
    "approved": true
}
